backend:
    name: git-gateway
    branch: main # The branch where Decap CMS will push changes

media_folder: 'src/assets/uploads' # Where uploaded media files are stored in your repository
public_folder: 'src/assets/uploads' # Public path to the media files
publish_mode: editorial_workflow # Enable save drafts and publish posts

collections:
    - name: 'blog'
      label: 'Blog Posts'
      folder: 'src/content/blog' # Path to your blog content
      create: true # Allow creation of new posts
      slug: '{{slug}}' # Slug for the post URLs
      fields:
          - label: 'Title'
            name: 'title'
            widget: 'string'
          - label: 'Excerpt'
            name: 'excerpt'
            widget: 'text'
          - label: 'Publish Date'
            name: 'publishDate'
            widget: 'datetime'
          - label: 'Canonical URL'
            name: 'canonical'
            widget: 'string'
            required: false
          - label: 'Tags'
            name: 'tags'
            widget: 'relation'
            collection: 'tags'
            search_fields: ['title']
            value_field: 'title'
            display_fields: ['title']
            multiple: true
            required: false
            allow_add: true
          - label: 'Image'
            name: 'image'
            widget: 'object'
            required: false
            fields:
                - label: 'Image Src'
                  name: 'src'
                  widget: 'image'
                  required: false
                - label: 'Alt Text'
                  name: 'alt'
                  widget: 'string'
                  required: false
          - label: 'Body'
            name: 'body'
            widget: 'markdown'

    - name: 'tags'
      label: 'Tags'
      folder: 'src/content/tags'
      create: true
      slug: '{{slug}}'
      fields:
          - label: 'Title'
            name: 'title'
            widget: 'string'
          - label: 'Body'
            name: 'body'
            widget: 'markdown'
          - label: 'Canonical URL'
            name: 'canonical'
            widget: 'string'
            required: false

    - name: 'faq'
      label: 'FAQ'
      folder: 'src/content/faq'
      create: true
      slug: '{{slug}}'
      fields:
          - label: 'Title'
            name: 'title'
            widget: 'string'
          - label: 'Body'
            name: 'body'
            widget: 'markdown'
          - label: 'Promoted to Homepage'
            name: 'promoted'
            widget: 'boolean'
            required: false
